public class Assets {
    static public void printTitle(){
        System.out.println("                    ████████  ██                          ███████             ████     ████                          █████                   ");
        System.out.println("                       ██     ██          ███              ██        █████      ██       ██                          ██   █                   ");
        System.out.println("                       ██     █████     ██   ██            ██████        ██     ██       ██                █████   ████                   ");
        System.out.println("                       ██     ██   ██   ███████            ██       ███████     ██       ██               ██   ██    ██                      ");
        System.out.println("                       ██     ██   ██   ██                 ██       ██   ██     ██       ██               ██   ██    ██                      ");
        System.out.println("                       ██     ██   ██   ██████             ██       ███████     ████     ████              █████   ██████                    ");
        System.out.println("                                                                                                                                             ");
        System.out.println("                                                                                                                                             ");
        System.out.println("                                                                                                                                             ");
        System.out.println("                                                                                                                                             ");
        System.out.println("        █████                                                                        ██                                                 ");
        System.out.println("      ███                                     ██                           ██                                            ████                ");
        System.out.println("      ██                 ██████     █████   ███████   █████    ███████   ███████    ███     ██████             ██████      ██       ███   ");
        System.out.println("      ██        █████    ██   ██   ██         ██          ██   ██   ██     ██        ██     ██   ██   █████    ██   ██     ██     ██   ██    ");
        System.out.println("      ██       ██   ██   ██   ██   ██████     ██     ███████   ██   ██     ██        ██     ██   ██  ██   ██   ██   ██     ██     ███████    ");
        System.out.println("      ██       ██   ██   ██   ██       ██     ██     ██   ██   ██   ██     ██        ██     ██   ██  ██   ██   ██   ██     ██     ██        ");
        System.out.println("       ██████   █████    ██   ██   █████       ████  ███████   ███  ██     █████     ███    ██   ██   █████    ██████      ████   ██████    ");
        System.out.println("                                                                                                               ██                            ");
        System.out.println("                                                                                                                                             ");
        
    }
    static public void printInfrantry(){                                                                                               
        System.out.println("                                     █                                                              ");
        System.out.println("                                   █    ██                                                          ");
        System.out.println("                                    ████                                                            ");
        System.out.println("                                    ████                                                            ");
        System.out.println("                                      ███  █                                                        ");
        System.out.println("                                       ██                                                           ");
        System.out.println("                                       ███                                                          ");
        System.out.println("                                        ██                                                          ");
        System.out.println("                                         ██                                                         ");
        System.out.println("                                         ███                                                        ");
        System.out.println("                                          ██                                                        ");
        System.out.println("                                           ██                                                       ");
        System.out.println("                                           ███                                                      ");
        System.out.println("                                            ██                     ██                               ");
        System.out.println("                                             ██                   █ █                               ");
        System.out.println("                                             ██ █                █  █                               ");
        System.out.println("                                           ██     █           ███████                               ");
        System.out.println("                                        ███       █         ███      ██                             ");
        System.out.println("                                     ███    ███████        ██ █        █                            ");
        System.out.println("                                   ██    ███    █          █       █ ██ █                           ");
        System.out.println("                                 ██    ███       ██        ███                                      ");
        System.out.println("                                █    ███         ███      ██ █ ██████████                           ");
                System.out.println("                             ██      █                  █   █  ██ █ █    █                          ");
        System.out.println("                           ██     ████  ████████████████████        ███                             ");
        System.out.println("                           █████    ██ █            █  █ █  ████ ███                                ");
        System.out.println("                           ██    ████   █           █  █  █ ██   █                                  ");
        System.out.println("                             ████████ ██            █  ██   █ █████                                 ");
        System.out.println("                                  ██ ██        █    ██          ██  █                               ");
        System.out.println("                                  █████████   █     ███    ███  ██ █  █    █████                    ");
        System.out.println("                                      ████  █      █               █     ████████                   ");
        System.out.println("                                         ███   ██ █  ████ ████   █ █    ██████  █                   ");
        System.out.println("                                                    █  █████  ████ █  ████████████                  ");
        System.out.println("                                          █ ███  ████           █   ██   █████████                  ");
        System.out.println("                                         ██     ██     █  █    ██  █  ████████████                  ");
        System.out.println("                                         █    ██ ██  █  █ █   ██   ███████ ██  ██                   ");
        System.out.println("                                        █  █ ██  █     █     ██   ███████ █ █████                   ");
        System.out.println("                                     █  █   ███ ███       █  ██  █  ████    ██ █ █                  ");
        System.out.println("                                   ███   ████ ██  █████████ ██      ██████████████                  ");
        System.out.println("                                 ██     ███  ███ █      █ ███    █  █████  ██████                   ");
        System.out.println("                                ██    ███         ███████ █████  █  █████ ████ █                    ");
        System.out.println("                                 ███████ ██ ██ █ █ █  ██  █ ████  █  █████ ██ ██                    ");
        System.out.println("                                       █ █ █    █    █       █ ██████ ███ █████                     ");
        System.out.println("                                       █     █      ██████    ██████ ████ ████                      ");
        System.out.println("                                        ████  █ █ ███     ████  █     ███ ███                       ");
        System.out.println("                                      █    ████████    ███  █    ██    ████                         ");
        System.out.println("                                      ███            ████         █                                 ");
        System.out.println("                                       █████████         ██   ███  ██                               ");
        System.out.println("                                     █ █  ██ ██           ███      ████                             ");
        System.out.println("                                     ███  █ ██         ███   ██████   █                             ");
        System.out.println("                                   ███   ███        ███ █  █████ █  ███                             ");
        System.out.println("                                  █ ███████      ████ ██ █   ███████                                ");
        System.out.println("                                  █ █     █      ███ ██ ████    █                                   ");
        System.out.println("                                 ███ █ ███        ██ █ ██                                           ");
        System.out.println("                                 █ █████          █  ███                                            ");
        System.out.println("                                 █████             █████                                            ");
        System.out.println("                                 █  ██             █   █                                            ");
        System.out.println("                                ██ ███             █████                                            ");
        System.out.println("                                ███  █               ███                                            ");
        System.out.println("                                ████████████████                                                    ");
        System.out.println("                          █████ █     ██    █  ███████                                              ");
        System.out.println("                        ███ █ █ ██████      █  █      █ ███                                         ");
        System.out.println("                       ██     █        ███            ██  █████                                     ");
        System.out.println("                        █  ██              █                  ███                                   ");
        System.out.println("                        ███       █    █         █   █ ███  ██  ██                                  ");
        System.out.println("                          █████ █   ██        ██  █             █                                   ");
        System.out.println("                              ██████      █        █       █ ███                                    ");
        System.out.println("                                    ██████████      █████████                                       ");
        System.out.println("                                              ██████                                                ");
                                                                                                  
    }
    static public void printCavalry(){
        System.out.println("                                                                                                     ");
        System.out.println("                           █                                                                        ");
        System.out.println("                        ███████                                                                     ");
        System.out.println("                         ████   ███                                                                 ");
        System.out.println("                                    █                                                                ");
        System.out.println("                                  ██  █                                                             ");
        System.out.println("                                    ██████                                                          ");
        System.out.println("                                   █     ███                                                        ");
        System.out.println("                                   █      ████                                                      ");
        System.out.println("                                   █            █                                                   ");
        System.out.println("                                   █    ██████ █                                                    ");
        System.out.println("                                   █████       █                                                    ");
        System.out.println("                                   ████  █    █                                                     ");
        System.out.println("                                    █  █    █████                                                   ");
        System.out.println("                                      ████ ██                                                       ");
        System.out.println("                                   ██ ██    █                                                       ");
        System.out.println("                                 ███       ████                                                     ");
        System.out.println("                              ██    █       █ ███                                                   ");
        System.out.println("                             ██     ████     ███ ██                                     ██   █      ");
        System.out.println("                             ██     █  █ ██   █   ██                      ███████     ███ ████      ");
        System.out.println("                             █      █      █ █ █   ██               ██████       ███████ ███        ");
        System.out.println("                             █    █ ██ ███    ██ █  █             █████ ███    ██    ███            ");
        System.out.println("                             ██████ ███         █   █           ██ ██          █ █████   ██         ");
        System.out.println("                             █      █ █ ██████ █     █        ████   ██████████████       ██        ");
        System.out.println("                            █       ██          █ █ ███      ███     █            █  ██████ ██      ");
        System.out.println("                          █ █████   ██        ███████  █    ██   █   ████ ████  █ █ ██  ████ █      ");
        System.out.println("                           █ █    ██   ████  █        █  █ ██ ██          █  ██    █ █████ ██       ");
        System.out.println("                           █  █   ███████████    ██    ███   █       █   ██████         █   ██      ");
        System.out.println("                           ██ ██  █ █           ██  ██  █  █     ██ ███████ ██ ██   ██   █  ██      ");
        System.out.println("                            ████████    █       █   ███ ██     █    █ █ ██  ████████         ██     ");
        System.out.println("                             █     ███████        ██ █  ██   █    █████ █  ██   ██ ████████   █     ");
        System.out.println("                               █  ██     ████████     █     █  ██  █ ██ █ ██   █  ███  █   █        ");
        System.out.println("                       █████████    █  █    █ █     █     ██  ██   █  █ █ █     ███ ██████ ██████   ");
        System.out.println("                   █████ ██   █████████      █   █  █ █ ████  █   █ █  █████     █    ████  █  █ █  ");
        System.out.println("            ████████ ██      ██     ██████   █   █   ██      █            █      █        █   ████  ");
        System.out.println("         ███████          █    █  █  █   █ █ █  ███ █   █   ██   ██  █   ██████         █ █ █ ███   ");
        System.out.println("       ███  ██  ███  ███      █████  ██     ██ █ █      ███   █ ██    █████ ███████████  █████      ");
        System.out.println("      █     █  █  █  █   ███      █  █ █    █  ███   ████  █    █     █          █    ████          ");
        System.out.println("     ████ ███  █ ██  █   ██   ███ ████ ██████ █  ████ █ █  █     ███████   █    ████                ");
        System.out.println("     ████████        █  █ █ █   █    █ █      █  █    █ █  █    █  ██  █████                        ");
        System.out.println("     ██ █████  █ ██  █  █   ███████  █       ██  █    █    █        █     ███                       ");
        System.out.println("      ██ ███   █     █  ██  █       ██████ ██ █ ██    █    █     █   █     ██                       ");
        System.out.println("      ████ █ █ ██ ██ █   █  █       ███ ████  █ ██  █ █    ██    █    █ ██████                      ");
        System.out.println("      ██ ███      █  ██ ██  █        ██       █ ██    █    ██  ███    ██    ██                      ");
        System.out.println("      ████ █ █ █  █  █   █  ██ ██████  █   ███  ████  █     █    █  ██  █   ██                      ");
        System.out.println("      ██████ █ █  █  ██  █  █   █  ██ ██     █   █    █     █    ██    █ █ ███                      ");
        System.out.println("      ██ ██  █ █  █  █   █  █  ██  ██ ██        ██    █     █     █  █ █ █████                      ");
        System.out.println("      ██  █    █  ██ ██  █  █   █  █   ██   █ █████    █    █     █    █   ███                      ");
        System.out.println("     ████ █       ██ ██  █  █   █  █   ███  ███ ███ ██ █     █    █       ██   █                    ");
        System.out.println("     █ █  █████   ████   █  ██  █  █ ██ █ █  █   ██          █    █  █   ██   ██                    ");
        System.out.println("    ███ █ █  ████    ████   ███ █  █ ████    █ █████ █  ███  █ ██ █   ███    █  █                   ");
        System.out.println("    █  ██ █ ██ ██     ███████ █████      ███████  ██ █  █    █    ██      ████                      ");
        System.out.println("     ██████ ██ ██      ██ ██  ███   ██ █ █         ████      █ ███████████████████                  ");
        System.out.println("    █  █  █ █  ██      ████  █████ ███     █           ████████            ███  ████                ");
        System.out.println("      ████     █       █  ██████████ ███████            ███ ███              ████ ██                ");
        System.out.println("    ██  █ █  ███      ████████████                      █     █                ███ ████             ");
        System.out.println("           █ ██        ██████ ███                       ███  ██                  ████████           ");
        System.out.println("          █ █           ████████                         ██  ██                    ████  █          ");
        System.out.println("                          ████                           ███ █                      ██████          ");
        System.out.println("                           ████                           █  ██                       ████          ");
        System.out.println("                          ██ ███                          ██████                       ███          ");
        System.out.println("                          ███████                         ██   █                       ████         ");
        System.out.println("                          ████████                        ███ ██                       ████         ");
        System.out.println("                          ████ █████                       ████                         ███         ");
        System.out.println("                          ████ ████                         ███                         ████        ");
        System.out.println("                          ████   ███                        ███                         █████       ");
        System.out.println("                          ████  █████                       ███                         ███ █       ");
        System.out.println("                         █████  ████                        ███                           ███       ");
        System.out.println("                           ███                              ████                        █████       ");
        System.out.println("                            ████ ███                        ██ ██                       █   █       ");
        System.out.println("                           █                                █████                       ██          ");
        System.out.println("                            ██████        ██                  ████                        ████      ");
        System.out.println("                                      ███                    ██   █                                 ");
        System.out.println("                                                              █                                     ");

    }
    static public void printCannon(){
    System.out.println("                                                                                                     ");
    System.out.println("                                                                                    █                ");
    System.out.println("                                                                                 ████ ██             ");
    System.out.println("                                                                                █     ███            ");
    System.out.println("                                                                             ███       ███           ");
    System.out.println("                                                                          ███       ██  █            ");
    System.out.println("                                                                      ████     █████████             ");
    System.out.println("                                                      ███          ███      ██████                   ");
    System.out.println("                                                   ███  █  ███ ████     ███████                      ");
    System.out.println("                                                 ██     ███  ██      ███████                         ");
    System.out.println("                                     ████████████     █   ██       █████                             ");
    System.out.println("                                  ██  ███████   █████  ██    ██████    █████                         ");
    System.out.println("                               ███  ███      ██      ███    ██  █████ ████████████                   ");
    System.out.println("                             ██  ███  █      ██ ████   ███   ██  █ ██      ██ ██████                 ");
    System.out.println("                            █  ███    ██     ██          ██  ██████████    █     █████               ");
    System.out.println("                           █  ██      ██  ████       ██   ██  ██████████  ██      ██████             ");
    System.out.println("                          █  █  █      ██   ██     ██      ██  █████  ███ █     ██  █████            ");
    System.out.println("                          █ ██   ██ █  ██   █    ██     █   █ ██   ████   █    █     █████           ");
    System.out.println("                         █  ██ ██ ███   ██ ██  ███   █████  █   ███    █ ██  ██       ████           ");
    System.out.println("                         █ ███      ███  █ ██ ██     ██      ██   █ ██ ███ ██       █████ █          ");
    System.out.println("                         █ ██          █████ ███      █ ██   ██   █    █████ ███████   ████          ");
    System.out.println("                           █  ███████  █    █   ████████     ████████████ ██           █ ██          ");
    System.out.println("                       ███ ██          █    ████████    ██   ██      ██████████        █ ██          ");
    System.out.println("                     █   █ ██        █ ███████  ██       █   ██  ███  ████ █    ████   ████          ");
    System.out.println("                    █    █ ███    █████  █ █ █    ████   █   ████    ██  █  ██      ██████           ");
    System.out.println("                   ███   █  ██ ████    ██  █  ██      ████  ██       █   █   ██       ████           ");
    System.out.println("                  ██        █  █    ████   █   ██        █  ███     █    █    ██     ████            ");
    System.out.println("                ███      █   ██   ██  █    █    ██      ██ █████   ██    ██    ██  █████             ");
    System.out.println("             ███            █ ████   █     █     ██    ██  █████████     ██      █████               ");
    System.out.println("    ██████████      ██████████  ██  ██     █      ██  ██ ███   ██████    ██   ███████                ");
    System.out.println("    ████████████████████      █  ████      ██      ███  ██       █████████████████                   ");
    System.out.println("                               ███ ████    ██     █   ███             ██████                         ");
    System.out.println("                                 ███  ███████ █████████                                              ");
    System.out.println("                                    ████████████████                                                 ");

    }

}